call pathogen#infect()
call pathogen#helptags()

set nocompatible

syntax on

" Don't show the intro message when starting Vim
set shortmess+=I

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

let moria_style='black'
colorscheme moria

" Tweaks for the moria colorscheme:
" ---------------------------------
"
" A crucial fix for stronger emphasis of the changes in a diff of similar lines
hi DiffText guibg=#8b008b

" A crucial fix for making the SignColumn visible (used by syntastic plugin)
hi SignColumn guibg=#25365a

" Adjust the listchars color to be darker and more subtle
hi SpecialKey guifg=#443311


" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" Enable mouse usage (all modes)
set mouse=a

" Right mouse button pops up a menu
set mousemodel=popup

" Command-line completion
set wildmenu
set wildmode=longest:list

" I rarely want to edit backup files. If I must then I can manually type the
" full name without wild completion
set wildignore+=*~

set wildignore+=_darcs/**

" Don't show a message on the last line when in insert or replace mode.  It's
" sometimes useful to go into insert mode without having an existing message
" that is there get cleared.
set noshowmode

" Show (partial) command in status line.
set showcmd

" Show matching brackets.
set showmatch

" Incremental search
set incsearch

" Highlight search matches
set hlsearch

" Always show a status line
set laststatus=2

" Automatically save before commands like :next and :make
set autowrite

" When I want to see if there are any tab characters I can :setl list
set listchars=tab:>-

" Jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

" Automatically open, but do not go to (if there are errors) the quickfix /
" location list window, or close it when is has become empty.
"
" Note: Must allow nesting of autocmds to enable any customizations for
" quickfix buffers.
" Note: Normally, :cwindow jumps to the quickfix window if the command opens it
" (but not if it's already open). However, as part of the autocmd, this doesn't
" seem to happen.
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

let mapleader=","

" Mapping for running a silent make
:map <Leader>j :silent make<CR>

" Key bindings for fugitive
nnoremap <Leader>gs :Gstatus<CR>
nnoremap <Leader>gd :Gdiff<CR>

" Key binding for NERDTree open/close
nnoremap <silent> <F8> :NERDTreeToggle<CR>

" Key binding for Tagbar open/close
nnoremap <silent> <F9> :TagbarToggle<CR>

" Key binding for ghcmod
au FileType haskell nnoremap <buffer> <F1> :GhcModType<CR>
au FileType haskell nnoremap <buffer> <F2> :GhcModTypeClear<CR>

" Key binding for make
nnoremap <silent> <F6> :make<CR>

let g:syntastic_mode_map =
      \ { 'mode': 'active',
      \   'passive_filetypes': ['haskell'] }

" Command-T configuration:
let g:CommandTMaxHeight=16
let g:CommandTMinHeight=9999
nnoremap <Leader>T :CommandTFlush<CR>

" Allow gui to be full height of screen. This also prevents the gui from
" acting buggy and not sizing itself correctly when using tiling window
" managers such as xmonad.
set guiheadroom=0

" Disable Toolbar
set guioptions-=T

" Disable all Scrollbars
set guioptions-=L
set guioptions-=r

" Python
au FileType python setl et ts=4 sw=4 sts=4
set wildignore+=*.pyc
set wildignore+=*.pyo

" C/C++
au FileType c,cpp setl et ts=4 sw=4 sts=4
set wildignore+=*.o
set wildignore+=*.d

" Vim
au FileType vim setl et ts=2 sw=2 sts=2

" ActionScript
au FileType actionscript setl et ts=4 sw=4 sts=4 cindent
au Bufread,BufNewFile *.as set filetype=actionscript

" Haskell
au FileType haskell setl et ts=4 sw=4 sts=4 autoindent smartindent
au Bufread,BufNewFile *.hsc set filetype=haskell
set wildignore+=*.o
set wildignore+=*.hi
set wildignore+=*.chi

" make
au FileType make setl list

" HTML Django
au FileType htmldjango setl et ts=2 sw=2 sts=2

" handlebars
au FileType handlebars setl et ts=2 sw=2 sts=2

" less
au FileType less setl et ts=2 sw=2 sts=2

" coffee
au FileType coffee setl et ts=2 sw=2 sts=2
