call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

set nocompatible

syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

let moria_style='black'
colorscheme moria

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" Enable mouse usage (all modes)
set mouse=a

" Right mouse button pops up a menu
set mousemodel=popup

" Command-line completion
set wildmenu
set wildmode=longest:list

" Show (partial) command in status line.
set showcmd

" Show matching brackets.
set showmatch

" Incremental search
set incsearch

" Highlight search matches
set hlsearch

" Always show a status line
set laststatus=2

" Automatically save before commands like :next and :make
set autowrite


" Automatically open, but do not go to (if there are errors) the quickfix /
" location list window, or close it when is has become empty.
"
" Note: Must allow nesting of autocmds to enable any customizations for
" quickfix buffers.
" Note: Normally, :cwindow jumps to the quickfix window if the command opens it
" (but not if it's already open). However, as part of the autocmd, this doesn't
" seem to happen.
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

" Mapping for running a silent make
:map <Leader>j :silent make<CR>

" Disable Toolbar
set guioptions-=T

" Python
au FileType python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Vim
au FileType vim setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

" ActionScript
au Bufread,BufNewFile *.as set filetype=actionscript
au FileType actionscript setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4 cindent

" Haskell .hsc file
au FileType haskell setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
au Bufread,BufNewFile *.hsc set filetype=haskell
